version: '3.9'

services:

  app-cittadino:
    image: drupal:9
    container_name: isp-cittadino
    ports:
      - 8001:80
    volumes:
      - ./volumes/drupal:/opt/drupal
    networks:
      -  isp-cittadino-network
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: drupal_admin
      DB_NAME: drupal
      DB_PASSWORD: SicariDrupal
      DB_PREFIX: 
  db:
    image: mysql:8
    container_name: isp-cittadino-db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_admin
      MYSQL_PASSWORD: SicariDrupal
      MYSQL_ROOT_PASSWORD: sicariDbAdmin
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - isp-cittadino-network
    restart: unless-stopped
 
networks: 
  isp-cittadino-network:
    driver: bridge
    name: isp-cittadino-network
