version: '3.9'

services:

  app-backoffice:
    image: drupal:9
    container_name: isp-backoffice
    ports:
      - 8000:80
    volumes:
      - ./volumes/drupal:/opt/drupal
    networks:
      -  isp-backoffice-network
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: drupal_admin
      DB_NAME: drupal
      DB_PASSWORD: SicariDrupal
      DB_PREFIX: 
  db:
    image: mysql:8
    container_name: isp-backoffice-db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_admin
      MYSQL_PASSWORD: SicariDrupal
      MYSQL_ROOT_PASSWORD: sicariDbAdmin
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - isp-backoffice-network
    restart: unless-stopped

networks: 
  isp-backoffice-network:
    name: network-ispettorato-backoffice
    driver: bridge
